on: [push]

name: Build Red Viper

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: build Red Viper
        run: make release
      - uses: actions/upload-artifact@v3
        with:
          name: red-viper.cia
          path: red-viper.cia
      - uses: actions/upload-artifact@v3
        with:
          name: red-viper.3dsx
          path: red-viper.3dsx
