on: [push]

name: Build r3Ddragon

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: build r3Ddragon
        run: make release
      - uses: actions/upload-artifact@v3
        with:
          name: r3Ddragon.cia
          path: r3Ddragon.cia
      - uses: actions/upload-artifact@v3
        with:
          name: r3Ddragon.3dsx
          path: r3Ddragon.3dsx
